service: amber-framework

plugins:
  - serverless-offline

provider:
  region: ap-southeast-1
  name: aws
  runtime: nodejs8.10
  memorySize: 2048
  versionFunctions: false
  environment: ${file(env.yml):${self:custom.stage}}
  timeout: 30

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  app:
    handler: src/app-serverless.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true